import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";


export const metadata: Metadata = {
  title: "Stay-Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <>
   <Navbar/>
        {children}
        <Toaster/>
     
   </>
        
  );
}
